# Generated by Django 5.2 on 2025-08-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="country",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(default="default@example.com", max_length=254, verbose_name="email address"),
            preserve_default=False,
        ),
    ]
