from django.urls import path

from .views import (
    AddPostView,
    CategoryListView,
    ContactView,
    GetSubcategoriesView,
    HomeView,
    PostDeleteView,
    PostDetailView,
    PostListView,
    PostsFreeListView,
    PostsInCategoryView,
    PostsPaidListView,
    PostUpdateView,
    PublishPostView,
    SubscriptionView,
    UnpublishPostView,
    subscription_success_view,
    subscription_view,
    category_detail_view,
    subcategory_detail_view,
    update_post_status,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("contacts/", ContactView.as_view(), name="contacts"),
    path("post_list/", PostListView.as_view(), name="post_list"),
    path("posts/free/", PostsFreeListView.as_view(), name="posts_free"),
    path("posts/paid/", PostsPaidListView.as_view(), name="posts_paid"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("add_post/", AddPostView.as_view(), name="add_post"),
    path("edit/<int:pk>/", PostUpdateView.as_view(), name="post_edit"),
    path("delete/<int:pk>/", PostDeleteView.as_view(), name="post_delete"),
    path("posts/publish/<int:pk>/", PublishPostView.as_view(), name="publish_post"),
    path("posts/unpublish/<int:pk>/", UnpublishPostView.as_view(), name="unpublish_post"),
    path("category/<int:pk>/posts/", PostsInCategoryView.as_view(), name="posts_in_category"),
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("subcategories/", GetSubcategoriesView.as_view(), name="get_subcategories"),
    path("subscription/", subscription_view, name="subscription"),
    path("api/subscription/", SubscriptionView.as_view(), name="api_subscription"),
    path("subscription/success/", subscription_success_view, name="subscription_success"),
    path('category/<int:category_id>/', category_detail_view, name='category_detail'),
    path('subcategory/<int:subcategory_id>/', subcategory_detail_view, name='subcategory_detail'),
    path('post/<int:post_id>/update/', update_post_status, name='update_post_status'),
]
